spring.datasource.url=jdbc:mysql://localhost:3306/partner-for-progress
spring.datasource.username=admin
spring.datasource.password=admin
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# Security Configuration
security.jwt.secret="this-is-a-512-bit-key-used-for-signing-jwt-tokens-that-should-be-changed-production"
security.jwt.expiration-in-ms=864000000

# Configuration for NYLAS mail, see https://www.nylas.com/
# It uses a connected Google account on which it sends mails
# For the credentials underneath, it will send mails from partnerforprogressdev@gmail.com
mail.grant-id = decd62e0-971f-401d-b1a2-41cbc3f75bb6
mail.authorization = Bearer nyk_v0_ohLhUHC66Gj8olpbbedYokyCD8CQeQYq8r29mcZTjJwONp1xEEoTDzbyGRGx2ryx
mail.sendMails = true
mail.partner-for-progress-email = partnerforprogressdev@google.com