spring.datasource.url=jdbc:postgresql://dpg-cvm5j1k9c44c73a83i5g-a.oregon-postgres.render.com/partnerforprogress_db
spring.datasource.username=partnerforprogress_db_user
spring.datasource.password=9bUiZhtN503RDw3X5bttpSqLSBG84TZg
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
server.port=${PORT:8080}


# Security Configuration
security.jwt.secret="this-is-a-512-bit-key-used-for-signing-jwt-tokens-that-should-be-changed-production"
security.jwt.expiration-in-ms=864000000

# Don't send mails by default in test
mail.grant-id = null
mail.authorization = null
mail.sendMails = false
mail.partner-for-progress-email = partnerforprogressdev@google.com

generate-dummy-data=true

logging.level.root=INFO
logging.level.org.springframework=DEBUG
